development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: log_viewer_development
  pool: 5
  host: 192.168.50.16
  username: develop
  password: password
  socket: /var/lib/mysql/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: log_viewer_test
  pool: 5
  host: 192.168.50.16
  username: develop
  password: password
  socket: /var/lib/mysql/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: log_viewer_production
  pool: 5
  host: localhost
  username: develop
  password: password
  socket: /var/lib/mysql/mysql.sock
